version: '3'

services:
  ms-crud-clientes:
    image: 'ms-crud-clientes:dev'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-crud-clientes
    depends_on:
      - db-clientes
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db-logistica
      - DB_PORT=5432
      - DB_NAME=ms-logistica-pedidos
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - shared_network

  db-clientes:
    image: postgres
    container_name: clientes-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ms-crud-clientes
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_network


volumes:
  postgres_data:

networks:
  shared_network:
    driver: bridge
    external: true
